# Generated by Django 5.1.4 on 2025-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_participant',
            old_name='joining_as',
            new_name='participant_type',
        ),
        migrations.RemoveField(
            model_name='form_participant',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='form_participant',
            name='team_member_count',
            field=models.CharField(blank=True, choices=[('two', 'Two'), ('three', 'Three')], max_length=5, null=True),
        ),
    ]
