# Generated by Django 5.1.4 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_joining_as_form_participant_participant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant',
            name='current_year',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
